# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160525_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=b'', help_text=b'Markdown accepted', verbose_name=b'About'),
        ),
    ]
