# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 02:38
from __future__ import unicode_literals

import autoslug.fields
from autoslug.utils import slugify
from django.db import migrations


def add_slug(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    for project in Project.objects.all():
        if not project.slug:
            project.slug = slugify(project.title)
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_slug'),
    ]

    operations = [
        migrations.RunPython(add_slug),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'title', unique=True),
        ),
    ]
