# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160524_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
