# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160524_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='date_requested',
            new_name='date_initiated',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='date_joined',
            new_name='date_involved',
        ),
        migrations.AddField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.IntegerField(choices=[(0, b'Owner'), (1, b'Leader'), (2, b'Involved'), (3, b'Interested')], default=3),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('user', 'project')]),
        ),
    ]
