# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organization_url',
            field=models.URLField(blank=True),
        ),
    ]
