# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_organization_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_year',
            field=models.IntegerField(default=0),
        ),
    ]
